import {
  IntegrationExecutionContext,
  IntegrationStepExecutionContext,
  StepExecutionContext,
} from './context';
import { IntegrationInstanceConfig } from './instance';

export interface StepStartState {
  /**
   * Indicates the step is disabled and should not be
   * executed by the state machine.
   */
  disabled: boolean;
}

export type StepStartStates = Record<string, StepStartState>;

export type GetStepStartStatesFunction<
  TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
> = (context: IntegrationExecutionContext<TConfig>) => StepStartStates;

export type ExecutionHandlerFunction<T extends StepExecutionContext> = (
  context: T,
) => Promise<void> | void;

export type IntegrationStepExecutionHandlerFunction<
  TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
> = ExecutionHandlerFunction<IntegrationStepExecutionContext<TConfig>>;
// > = (context: IntegrationStepExecutionContext<TConfig>) => Promise<void> | void;

export enum IntegrationStepResultStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PARTIAL_SUCCESS_DUE_TO_DEPENDENCY_FAILURE = 'partial_success_due_to_dependency_failure',
  DISABLED = 'disabled',
  PENDING_EVALUATION = 'pending_evaluation',
}

export type Step<
  TStepExecutionContext extends StepExecutionContext
> = StepMetadata & {
  executionHandler: ExecutionHandlerFunction<TStepExecutionContext>;
};

export type IntegrationStep<
  TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
> = StepMetadata & Step<IntegrationStepExecutionContext<TConfig>> & {};

// export type IntegrationStep<
//   TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
// > = StepMetadata & {
//   /**
//    * Function that runs to perform the stpe that
//    */
//   executionHandler: IntegrationStepExecutionHandlerFunction<TConfig>;
// };

export type IntegrationStepResult = StepMetadata & {
  status: IntegrationStepResultStatus;
};

interface StepMetadata {
  /*
   * Identifier used to reference and track steps
   */
  id: string;

  /**
   * Friendly name that will be displayed in debug logs
   * and to customers in the job event log.
   */
  name: string;

  /**
   * Entity or relationship types that are expected to be
   * generated by this step
   */
  types: string[];

  /**
   * An optional array of other step ids that need to execute
   * before the current step can.
   */
  dependsOn?: string[];
}
