/* eslint-disable */
import { Key } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A key used to grant access, such as ssh-key, access-key, api-key/token, mfa-token/device, etc.
 */
export type AccessKey = Key & {
  [k: string]: unknown;
};
