/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An application endpoint is a program interface that either initiates or receives a request, such as an API.
 */
export type ApplicationEndpoint = Entity & {
  /**
   * The endpoint address (e.g. an URI/URL, hostname)
   */
  address: string;
  [k: string]: unknown;
};
