/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A code deploy job.
 */
export type CodeDeploy = RecordEntity & {
  /**
   * Build/deploy job name.
   */
  jobName?: string;
  /**
   * Build/deploy job number.
   */
  jobNumber?: number;
  /**
   * Descriptive text of the job.
   */
  summary?: string;
  /**
   * Deploy action (e.g. plan, apply, destroy, rollback).
   */
  action?: string;
  /**
   * Name of the target system or environment.
   */
  target?: string;
  /**
   * Indicates if this is a production deploy, defaults to true.
   */
  production?: boolean;
  [k: string]: unknown;
};
