/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A software module. Such as an npm_module or java_library.
 */
export type CodeModule = Entity & {
  /**
   * Indicates if this is a public module.
   */
  public?: boolean;
  [k: string]: unknown;
};
