/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A standard unit of software that packages up code and all its dependencies and configurations.
 */
export type Container = Entity & {
  /**
   * The container image that the container is built from
   */
  image?: string;
  /**
   * The version of the Docker Engine
   */
  dockerVersion?: string;
  [k: string]: unknown;
};
