/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An technical or operational policy with rules that govern (or enforce, evaluate, monitor) a security control.
 */
export type ControlPolicy = Entity & {
  /**
   * The category of policy.
   */
  category?: 'compliance' | 'config' | 'password' | 'other';
  /**
   * Rules of policy.
   */
  rules?: string[];
  /**
   * Contents of the raw rules, if applicable.
   */
  content?: string;
  [k: string]: unknown;
};
