/* eslint-disable */
import { Key } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A key used to perform cryptographic functions, such as an encryption key.
 */
export type CryptoKey = Key & {
  [k: string]: unknown;
};
