/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An individual collection of data. The collection may exist in various formats, such as a table (e.g. a MySQL table). The exact data type is described in the _type property of the Entity.
 */
export type DataCollection = Entity & {
  /**
   * Indicates if this data table contains Personally Identifiable Information
   */
  PII?: boolean;
  /**
   * Indicates if this data table contains Protected Health Information
   */
  PHI?: boolean;
  /**
   * Indicates if this data table contains Payment Card Information
   */
  PCI?: boolean;
  /**
   * If the objects in the table need to be encrypted
   */
  encryptionRequired?: boolean;
  /**
   * If the data in the table is encrypted
   */
  encrypted?: boolean;
  /**
   * Indicates if the data table is open to public access
   */
  public?: boolean;
  [k: string]: unknown;
};
