/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A deployment of code, application, infrastructure or service. For example, a Kubernetes deployment. An auto scaling group is also considered a deployment.
 */
export type Deployment = Entity & {
  /**
   * Desired size (i.e. number of instances) associated with this deployment.
   */
  desiredSize?: number;
  /**
   * Current size (i.e. number of instances) active with this deployment.
   */
  currentSize?: number;
  /**
   * Maximum size (i.e. number of instances) limited by this deployment.
   */
  maxSize?: number;
  [k: string]: unknown;
};
