/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Directory, such as LDAP or Active Directory.
 */
export type Directory = Entity & {
  /**
   * Directory type.
   */
  type?: string;
  /**
   * List of directory servers.
   */
  directoryServers?: string[];
  /**
   * List of domain controllers.
   */
  domainControllers?: string[];
  /**
   * Parent directory, if the entity is a sub-directory.
   */
  parent?: string;
  [k: string]: unknown;
};
