/* eslint-disable */
import { DataStore } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A disk storage device such as an AWS EBS volume
 */
export type Disk = DataStore;
