/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A document or data object.
 */
export type Document = Entity & {
  /**
   * The name of the product this document is applicable to. This reference is used when the document is product related, such as a product requirement document (PRD) or software bill-of-materials (SBOM).
   */
  product?: string;
  /**
   * The version of this document.
   */
  version?: string;
  [k: string]: unknown;
};
