/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An internet domain.
 */
export type Domain = Entity & {
  /**
   * Domain name.
   */
  domainName: string;
  /**
   * WHOIS server that is responsible for resolving the details of this domain.
   */
  whoisServer?: string;
  /**
   * Domain registrar where this domain is registered.
   */
  registrar?: string;
  /**
   * Domain registrar name.
   */
  registrarName?: string;
  /**
   * Domain registrar URL.
   */
  registrarUrl?: string;
  /**
   * List of nameservers.
   */
  nameservers?: string[];
  /**
   * List of contact emails.
   */
  contactEmails?: string[];
  /**
   * Abuse contact email.
   */
  abuseContactEmail?: string;
  /**
   * Registrant contact email.
   */
  registrantContactEmail?: string;
  /**
   * Technical contact email.
   */
  techContactEmail?: string;
  /**
   * Administrative contact email.
   */
  adminContactEmail?: string;
  /**
   * Billing contact email.
   */
  billingContactEmail?: string;
  /**
   * Indicates whether auto-renewal is configured.
   */
  autoRenew?: boolean;
  /**
   * Indicates whether domain transfer is locked/protected.
   */
  locked?: boolean;
  /**
   * Parent domain, if the entity is a sub-domain.
   */
  parent?: string;
  [k: string]: unknown;
};
