/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A piece of hardware or software that protects a network/host/application.
 */
export type Firewall = Entity & {
  /**
   * The category of the Firewall. Indicates the scope that the Firewall applies to -- i.e. Network, Host, Application.
   */
  category: ('network' | 'host' | 'application' | 'other')[];
  /**
   * Indicates if the rules in the firewall is stateful.
   */
  isStateful?: boolean;
  [k: string]: unknown;
};
