/* eslint-disable */
import { GraphObject } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An object to represent a standard compliance or technical security framework.
 */
export type Framework = GraphObject & {
  /**
   * Name of this entity
   */
  name: string;
  /**
   * Display name
   */
  displayName: string;
  /**
   * A summary / short description of this entity.
   */
  summary?: string;
  /**
   * An extended description of this entity.
   */
  description?: string;
  /**
   * The name of the framework standard.
   */
  standard: string;
  /**
   * The version of the framework. For example, OWASP may have version 2010, 2013, 2017.
   */
  version: string;
  [k: string]: unknown;
};
