/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A virtual application function. For example, an aws_lambda_function, azure_function, or google_cloud_function
 */
export type Function = Entity & {
  /**
   * The image of this function, typically refers to a zip package.
   */
  image?: string;
  /**
   * The version of this function.
   */
  version?: string;
  /**
   * The runtime of this function. For example: 'nodejs6.10', 'nodejs8.10', or 'python2.7'.
   */
  runtime?: string;
  /**
   * The allocated memory of this function to execute.
   */
  memorySize?: string;
  /**
   * The size of code of this function.
   */
  codeSize?: string;
  /**
   * The hash of code of this function.
   */
  codeHash?: string;
  /**
   * What triggers this function to execute.
   */
  trigger?: string;
  /**
   * The handler of this function
   */
  handler?: string;
  [k: string]: unknown;
};
