/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A gateway/proxy that can be a system/appliance or software service, such as a network router or application gateway.
 */
export type Gateway = Entity & {
  /**
   * The category of the Gateway (corresponds to which OSI layer does the Proxy operates at).
   */
  category: ('network' | 'application' | 'data' | 'other')[];
  /**
   * The function of the Gateway
   */
  function: (
    | 'routing'
    | 'nat'
    | 'api-gateway'
    | 'content-filtering'
    | 'content-distribution'
    | 'load-balancing'
    | 'firewall'
    | 'ssl-termination'
    | 'reverse-proxy'
    | 'remote-access-gateway'
    | 'application-protection'
    | 'intrusion-detection'
    | 'intrusion-prevention'
    | 'mail-filtering'
    | 'malware-protection'
    | 'other'
  )[];
  /**
   * Indicates if the Gateway is open to public access
   */
  public: boolean;
  [k: string]: unknown;
};
