/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A defined, generic group of Entities. This could represent a group of Resources, Users, Workloads, DataRepositories, etc.
 */
export type Group = Entity & {
  [k: string]: unknown;
};
