/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A system image. For example, an AWS AMI (Amazon Machine Image).
 */
export type Image = Entity & {
  [k: string]: unknown;
};
