/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An re-assignable IpAddress resource entity. Do not create an entity for an IP Address _configured_ on a Host. Use this only if the IP Address is a reusable resource, such as an Elastic IP Address object in AWS.
 */
export type IpAddress = Entity & {
  /**
   * The assigned DNS name
   */
  dnsName?: string;
  /**
   * The assigned IP address
   */
  ipAddress: string;
  /**
   * The assigned public IP address
   */
  publicIpAddress?: string;
  /**
   * The assigned private IP address
   */
  privateIpAddress?: string;
  /**
   * Indicates IP version 4 or 6
   */
  ipVersion?: 4 | 6;
  [k: string]: unknown;
};
