/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A system of postulates, data, and inferences presented as a mathematical description of an entity or state of affairs. For example, a machine learning model.
 */
export type Model = Entity & {
  /**
   * Indicates whether the model is encrypted
   */
  encrypted?: boolean;
  [k: string]: unknown;
};
