/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An re-assignable software defined network interface resource entity. Do not create an entity for a network interface _configured_ on a Host. Use this only if the network interface is a reusable resource, such as an Elastic Network Interface object in AWS.
 */
export type NetworkInterface = Entity & {
  /**
   * The assigned MAC address
   */
  macAddress?: string;
  /**
   * The assigned DNS name
   */
  dnsName?: string;
  /**
   * The assigned primary IP address
   */
  ipAddress?: string;
  /**
   * The assigned public IP address
   */
  publicIpAddress?: string;
  /**
   * The assigned private IP address
   */
  privateIpAddress?: string;
  /**
   * Indicates IP version 4 or 6
   */
  ipVersion?: 4 | 6;
  [k: string]: unknown;
};
