/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An entity that represents an actual person, such as an employee of an organization.
 */
export type Person = Entity & {
  /**
   * The person's official first name in the system (such as HR database)
   */
  firstName: string;
  /**
   * The person's official last name in the system (such as HR database)
   */
  lastName: string;
  /**
   * The person's official middle name in the system (such as HR database)
   */
  middleName?: string;
  /**
   * The email addresses of the person; the first one in the array is the primary email.
   */
  email: string[];
  /**
   * The domain portion of the email addresses associated with the user account.
   */
  emailDomain?: string[];
  /**
   * The person's role or title within an organization
   */
  title?: string;
  /**
   * The person's phone numbers; the first one in the array is the primary contact number.
   */
  phone?: string[];
  /**
   * The person's physical contact address
   */
  address?: string;
  /**
   * The person's employee ID/number within an organization
   */
  employeeId?: string;
  /**
   * The type of employment
   */
  employeeType?: string;
  /**
   * One or more user Ids associated with this person
   */
  userIds?: string[];
  /**
   * Name of the person's manager
   */
  manager?: string;
  /**
   * Employee ID of the person's manager
   */
  managerId?: string;
  /**
   * Email of the person's manager
   */
  managerEmail?: string;
  /**
   * Timestamp of the background and/or reference check
   */
  backgroundCheckedOn?: number;
  /**
   * The agency or person conducted the background/reference check
   */
  backgroundCheckedBy?: string;
  [k: string]: unknown;
};
