/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A written policy documentation.
 */
export type Policy = RecordEntity & {
  /**
   * Title of the policy
   */
  title: string;
  /**
   * Summary or overview the describes the policy. Summary text is intended as guidance to the author and not included in the published version.
   */
  summary: string;
  /**
   * Author of the record
   */
  author?: string;
  /**
   * Text content of the policy. For policies/procedures used by the Policy Builder app, this will contain the template text in markdown format. Stored in raw data.
   */
  content: string;
  /**
   * Indicates if policy or procedure is applicable based on the organization's current risk and compliance needs. A Policy that is not applicable may become applicable later as the organization's requirements and maturity change.
   */
  applicable?: boolean;
  /**
   * Indicates if policy or procedure has been adopted. Only adopted policies and procedures are included in the published view of the Policy Builder app.
   */
  adopted?: boolean;
  [k: string]: unknown;
};
