/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A pull request.
 */
export type PR = RecordEntity & {
  /**
   * The title text of the PR.
   */
  title: string;
  /**
   * The summary text of the PR.
   */
  summary?: string;
  /**
   * The state of the PR.
   */
  state: string;
  /**
   * The source branch.
   */
  source: string;
  /**
   * The target/destination branch.
   */
  target: string;
  /**
   * The name of the CodeRepo this PR belongs to.
   */
  repository: string;
  /**
   * Indicates if every commit associated with this PR has been approved by a reviewer other than the code author.
   */
  approved?: boolean;
  /**
   * Indicates if every commit associated with this PR was submitted by a validated author known to the organization.
   */
  validated?: boolean;
  [k: string]: unknown;
};
