/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A software development project. Can be used for other generic projects as well but the defined properties are geared towards software development projects.
 */
export type Project = Entity & {
  /**
   * A defined project key. It is ideal for a code project to have a consistent key that matches that of issue tracking project. For example, the key for a Bitbucket project should match the key of its corresponding Jira project.
   */
  key?: string;
  /**
   * The Production URL
   */
  productionURL?: string;
  /**
   * The Non-Production / Staging URL
   */
  stagingURL?: string;
  /**
   * The Development URL
   */
  devURL?: string;
  /**
   * The Test URL
   */
  testURL?: string;
  /**
   * The additional URLs related to this application.
   */
  alternateURLs?: string[];
  [k: string]: unknown;
};
