/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A repository that contains resources. For example, a Docker container registry repository hosting Docker container images.
 */
export type Repository = Entity & {
  /**
   * Indicates if this is a public repo.
   */
  public?: boolean;
  [k: string]: unknown;
};
