/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A generic assignable resource. A resource is typically non-functional by itself unless used by or attached to a host or workload.
 */
export type Resource = Entity & {
  [k: string]: unknown;
};
