/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An object that represents an identified Risk as the result of an Assessment. The collection of Risk objects in JupiterOne make up the Risk Register. A Control may have a `MITIGATES` relationship to a Risk.
 */
export type Risk = RecordEntity & {
  /**
   * The name/id of the assessment that produced this risk.
   */
  assessment?: string;
  /**
   * The category (or area) of the risk. For example, 'process maturity' or 'natural disaster'.
   */
  category?: string;
  /**
   * Probability rating of the risk: '3: high/certain', '2: medium/likely', '1: low/unlikely', '0: none/negligible'.
   */
  probability: number;
  /**
   * Impact rating. '3: high/severe', '2: medium/moderate', '1: low/minor', '0: none/insignificant'.
   */
  impact: number;
  /**
   * Overall Risk Score = Probability x Impact
   */
  score: number;
  /**
   * Additional details to describe the risk.
   */
  details?: string;
  /**
   * Description of the mitigation, either planned or implemented, if applicable.
   */
  mitigation?: string;
  /**
   * Current status of this documented risk. Default status is `open`.
   */
  status: string;
  [k: string]: unknown;
};
