/* eslint-disable */
import { GraphObject } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The root node in the graph. There should be only one Root node per organization account.
 */
export type Root = GraphObject & {
  /**
   * Display name
   */
  displayName?: string;
  [k: string]: unknown;
};
