/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An operational or configuration compliance rule, often part of a Ruleset.
 */
export type Rule = Entity & {
  /**
   * The category of ruleset.
   */
  category?: string;
  /**
   * Contents of the rule, if applicable.
   */
  content?: string;
  [k: string]: unknown;
};
