/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A system vulnerability, application code or network infrastructure scanner.
 */
export type Scanner = Entity & {
  /**
   * The category of scanner
   */
  category: string[];
  [k: string]: unknown;
};
