/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A stored encrypted secret, accessed by permitted users or applications.
 */
export type Secret = Entity & {
  [k: string]: unknown;
};
