/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The physical location of an organization. A Person (i.e. employee) would typically has a relationship to a Site (i.e. located_at or work_at). Also used as the abstract reference to AWS Regions.
 */
export type Site = Entity & {
  /**
   * Type of site
   */
  category?: string[];
  /**
   * The address/location of the site. Or an AWS Region (e.g. us-east-2).
   */
  location?: string;
  /**
   * Hours of operation. e.g. M-F 9am-6pm
   */
  hours?: string;
  /**
   * Indicates the site is secured with physical controls such as key card access and surveillance cameras.
   */
  secured?: boolean;
  /**
   * Indicates that access to the site is restricted (a level above secured access).
   */
  restricted?: boolean;
  [k: string]: unknown;
};
