/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An object to represent a standard such as a compliance or technical standard.
 */
export type Standard = Entity & {
  /**
   * The name of the standard.
   */
  name: string;
  /**
   * The version of the standard. For example, OWASP may have version 2010, 2013, 2017.
   */
  version: string;
  [k: string]: unknown;
};
