/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A subscription to a service or channel.
 */
export type Subscription = Entity & {
  /**
   * Indicates whether the subscription is authenticated.
   */
  authenticated?: boolean;
  /**
   * Indicates whether the subscription is pending.
   */
  pending?: boolean;
  [k: string]: unknown;
};
