/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A collection of secrets such as a key ring
 */
export type Vault = Entity & {
  /**
   * Name of the vault
   */
  name: string;
  [k: string]: unknown;
};
