/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An external organization that is a vendor or service provider.
 */
export type Vendor = Entity & {
  /**
   * The category of vendor.
   */
  category: string | string[];
  /**
   * The vendor's main website URL.
   */
  website?: string;
  /**
   * List of business departments the vendor provides service for (e.g. IT, HR, Finance, Marketing, Development/Engineering, Security).
   */
  departments?: string[];
  /**
   * The email domain for the vendor (e.g. @jupiterone.io).
   */
  emailDomain?: string;
  /**
   * The vendor's point of contact person.
   */
  mainContactName?: string;
  /**
   * Email of the vendor's point of contact person.
   */
  mainContactEmail?: string;
  /**
   * Phone number of the vendor's point of contact person.
   */
  mainContactPhone?: string;
  /**
   * Main physical/mailing address of the vendor.
   */
  mainContactAddress?: string;
  /**
   * The title of the vendor's main point of contact. For example, 'Manager of Operations'.
   */
  mainContactTitle?: string;
  /**
   * The vendor's alternate/secondary point of contact person.
   */
  alternateContactName?: string;
  /**
   * Email of the vendor's alternate/secondary point of contact person.
   */
  alternateContactEmail?: string;
  /**
   * Phone number of the vendor's alternate/secondary point of contact person.
   */
  alternateContactPhone?: string;
  /**
   * Alternate/secondary physical/mailing address of the vendor.
   */
  alternateContactAddress?: string;
  /**
   * The title of the vendor's alternate/secondary point of contact. For example, 'CISO'.
   */
  alternateContactTitle?: string;
  /**
   * List of admin users to the vendor account, if applicable. If this vendor account is integrated directly to JupiterOne and its data is ingested, the admin users should be already mapped as User entities.
   */
  admins?: string[];
  /**
   * The number of days the vendor agrees to report an identified data breach, per vendor agreement and/or SLA. This is typically 3 to 30 days. Note that GDPR requires breach notification within 3 days / 72 hours.
   */
  breachResponseDays?: number;
  /**
   * Link to Non-Disclosure Agreement (NDA) document.
   */
  linkToNDA?: string;
  /**
   * Link to Master Service Agreement (MSA) document.
   */
  linkToMSA?: string;
  /**
   * Link to Service Level Agreement (SLA) document.
   */
  linkToSLA?: string;
  /**
   * Link to Business Associate Agreement (BAA) document - for HIPAA only.
   */
  linkToBAA?: string;
  /**
   * Link to GDPR Data Processing Addendum (DPA) document - for GDPR only.
   */
  linkToDPA?: string;
  /**
   * Link to the external vendor technology risk (VTR) report.
   */
  linkToVTR?: string;
  /**
   * Link to the external information security assessment (ISA) report.
   */
  linkToISA?: string;
  /**
   * Link to the vendor's service status page (e.g. https://status.aws.amazon.com/).
   */
  statusPage?: string;
  /**
   * The timestamp (in milliseconds since epoch) of when this vendor was last validated per the vendor management policy.
   */
  validatedOn?: number;
  [k: string]: unknown;
};
