/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A virtual compute instance, it could be an aws-ec2-instance, a docker-container, an aws-lambda-function, an application-process, or a vmware-instance. The exact workload type is described in the _type property of the Entity.
 */
export type Workload = Entity & {
  /**
   * The image this workload is derived from, such as an AMI or docker image. At the abstract level, this usually maps to the _id of a Resource.
   */
  image?: string;
  /**
   * The fully qualified domain name of attached to the instance, if applicable
   */
  fqdn?: string;
  [k: string]: unknown;
};
