/* eslint-disable */
import { RecordEntity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A notice of any unusual or dangerous circumstance that is sent to responsible parties for the purpose of triggering action.
 */
export type Alert = RecordEntity;
