/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An individual data object, such as an aws-s3-object, sharepoint-document, source-code, or a file (on disk). The exact data type is described in the _type property of the Entity.
 */
export type DataObject = Entity & {
  /**
   * A user-provided category of the data, such as 'Source Code', 'Report', 'Patent Application', 'Business Plan', 'Customer Record', 'Genetic Data', etc.
   */
  category?: string;
  /**
   * The format of the data, such as 'document', 'raw', 'plaintext', 'binary', etc.
   */
  format?: string;
  /**
   * URI to the data, e.g. file path
   */
  location?: string;
  /**
   * Indicates if this data object is or contains Personally Identifiable Information
   */
  PII?: boolean;
  /**
   * Indicates if this data object is or contains Protected Health Information
   */
  PHI?: boolean;
  /**
   * Indicates if this data object is or contains Payment Card Information
   */
  PCI?: boolean;
  /**
   * If the data needs to be encrypted
   */
  encryptionRequired?: boolean;
  /**
   * If the data is encrypted
   */
  encrypted?: boolean;
  /**
   * Indicates if the data object is open to public access
   */
  public?: boolean;
  [k: string]: unknown;
};
