/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An issue as used by GitHub, Jira, or other project trackers.
 */
export type Issue = Entity & {
  [k: string]: unknown;
};
