/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A specific repository or destination containing application, network, or system logs.
 */
export type Logs = Entity & {
  /**
   * The type of logs
   */
  type?: string;
  [k: string]: unknown;
};
