/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A product developed by the organization, such as a software product.
 */
export type Product = Entity & {
  /**
   * Category that defines the product (e.g. 'web', 'mobile').
   */
  category?: string;
  /**
   * Description of the product
   */
  description?: string;
  /**
   * App links/URLs related to this product.
   */
  appLink?: string[];
  /**
   * Link to the status page of this product (for a SaaS product).
   */
  statusPage?: string[];
  /**
   * Project key(s) that reference a Jira project, Bitbucket project, or similar related to this product.
   */
  projectKey?: string[];
  [k: string]: unknown;
};
