/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An operational or configuration compliance ruleset with rules that govern (or enforce, evaluate, monitor) a security control or IT system.
 */
export type Ruleset = Entity & {
  /**
   * The category of ruleset.
   */
  category?: string;
  /**
   * Rules of ruleset. Each rule is written 'as-code' that can be operationalized with a control provider or within JupiterOne's rules engine.
   */
  rules?: string[];
  /**
   * Contents of the raw rules, if applicable.
   */
  content?: string;
  [k: string]: unknown;
};
