/* eslint-disable */
import { Entity } from './Base';

/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A user account/login to access certain systems and/or services. Examples include okta-user, aws-iam-user, ssh-user, local-user (on a host), etc.
 */
export type User = Entity & {
  /**
   * Username
   */
  username?: string;
  /**
   * The primary email address associated with the user account
   */
  email?: string;
  /**
   * The domain portion of the email addresses associated with the user account.
   */
  emailDomain?: string[];
  /**
   * The shortened login Id. For example, if the username is the full email address (first.last@company.com), the shortLoginId would be the part before @ (first.last).
   */
  shortLoginId?: string;
  /**
   * Specifies whether multi-factor authentication (MFA) is enabled for this user.
   */
  mfaEnabled?: boolean;
  /**
   * Specifies what type of multi-factor authentication (MFA) is being used by this user.
   */
  mfaType?: string;
  /**
   * Specifies whether user account is active or disabled.
   */
  active?: boolean;
  /**
   * The user's official first name in the system (such as HR database)
   */
  firstName?: string;
  /**
   * The user's official last name in the system (such as HR database)
   */
  lastName?: string;
  /**
   * The timestamp (in milliseconds since epoch) of when the user's password was last rotated for this particular account.
   */
  passwordChangedOn?: number;
  [k: string]: unknown;
};
