name: Alpha Release
on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # Publishing is done in a separate job to allow
  # for all matrix builds to complete.
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: yarn
          registry-url: https://registry.npmjs.org

      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn --frozen-lock-file
          yarn lerna publish --canary --no-verify-access --yes
