name: Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Check out code repository source code
        uses: actions/checkout@v2

      - id: setup-node
        name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: yarn

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests
        run: yarn test:ci

      - name: Run build
        run: yarn build:dist

  # Publishing is done in a separate job to allow
  # for all matrix builds to complete.
  release:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      fail-fast: false

    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: yarn

      # Fetch tags and describe the commit before the merge commit
      # to see if it's a version publish
      - name: Fetch tags
        run: |
          git fetch --tags
          if git describe --exact-match --match "v[0-9]*.[0-9]*.[0-9]*" HEAD^2
          then
            echo "Found version commit tag. Publishing."
            echo "publish=true" >> $GITHUB_ENV
          else
            echo "Version commit tag not found. Not publishing."
          fi

      - name: Publish
        if: env.publish == 'true'
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" > .npmrc
          yarn --frozen-lock-file
          yarn lerna publish from-package --no-verify-access --yes
