import {
  ExecutionContext,
  IntegrationStepExecutionContext,
  StepExecutionContext,
} from './context';
import { IntegrationInstanceConfig } from './instance';

export interface StepStartState {
  /**
   * Indicates the step is disabled and should not be
   * executed by the state machine.
   */
  disabled: boolean;
}

export type StepStartStates = Record<string, StepStartState>;

export type GetStepStartStatesFunction<T extends ExecutionContext> = (
  context: T,
) => StepStartStates | Promise<StepStartStates>;

export type ExecutionHandlerFunction<T extends StepExecutionContext> = (
  context: T,
) => Promise<void> | void;

export type StepExecutionHandlerFunction<
  TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
> = ExecutionHandlerFunction<IntegrationStepExecutionContext<TConfig>>;

export enum StepResultStatus {
  SUCCESS = 'success',
  FAILURE = 'failure',
  PARTIAL_SUCCESS_DUE_TO_DEPENDENCY_FAILURE = 'partial_success_due_to_dependency_failure',
  DISABLED = 'disabled',
  PENDING_EVALUATION = 'pending_evaluation',
}

export type Step<T extends StepExecutionContext> = StepMetadata & {
  /**
   * Function that runs to perform the stpe that
   */
  executionHandler: ExecutionHandlerFunction<T>;
};

export type IntegrationStepResult = Omit<StepMetadata, 'types'> & {
  status: StepResultStatus;

  /**
   * Entity or relatioship types that were declared
   * when the step was configured.
   */
  declaredTypes: string[];

  /**
   * Entity or relationship types that were encountered during
   * the step's execution.
   */
  encounteredTypes: string[];
};

export type IntegrationStep<
  TConfig extends IntegrationInstanceConfig = IntegrationInstanceConfig
> = StepMetadata & Step<IntegrationStepExecutionContext<TConfig>>;

export interface StepMetadata {
  /*
   * Identifier used to reference and track steps
   */
  id: string;

  /**
   * Friendly name that will be displayed in debug logs
   * and to customers in the job event log.
   */
  name: string;

  /**
   * Entity or relationship types that are expected to be
   * generated by this step
   */
  types: string[];

  /**
   * An optional array of other step ids that need to execute
   * before the current step can.
   */
  dependsOn?: string[];
}
